apiVersion: apps/v1
kind: Deployment
metadata:
 name: modeloxd-deployment
spec:
  selector:
    matchLabels:
      app: modeloxd-server
  replicas: 1
  template:
    metadata:
      labels:
        app: modeloxd-server
    spec:
      containers:
      - name: modeloxd-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/{jairdelfin}/tensorflow-{modeloxd}:{github.sha}
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: modeloxd-service
  name: modeloxd-service
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: modeloxd-server
  type: LoadBalancer
