apiVersion: apps/v1
kind: Deployment
metadata:
  name: modeloxd-deployment
spec:
  selector:
    matchLabels:
      app: modeloxd-server
  replicas: 1
  template:
    metadata:
      labels:
        app: modeloxd-server
    spec:
      containers:
      - name: modeloxd-container
        image: docker.io/{jairdelfin}/{modeloxd}:{github.sha}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: modeloxd-service
  name: modeloxd-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: modeloxd-server
  type: LoadBalancer
